modules: quickshell: Fix outdated name kde6
Name 'kde6' is no longer valid in Nix. It was replaced with 'kde'.
Warning in home build process:
> evaluation warning: The qt.platformTheme.name value "kde6" has been deprecated and renamed to "kde".
This condition prevents QuickShell from working:
> ERROR: caused by ... module "Qt5Compat.GraphicalEffects" is not installed
Fix by changing 'kde6' to 'kde'.

Signed-off-by: Elisa K. K. <mika@sob.moe>